name: Ubuntu-Server
on:
  push:
    branches: [ main ] 
    paths-ignore: 'README.md' 
  workflow_dispatch:
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "sepamm1234@gmail.com"
  GitHubName: "kidzz26" 
  Branch: "main"
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Initializing environment
      run: |
        git config --global user.name "kidzz26"
        git config --global user.email "sepamm1234@gmail.com"               
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex curl bison aria2
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo
        git clone https://github.com/Hostfl/ssh ssh && cd ssh && bash *.sh
    
    - name: Set Git Configs & Secrets
      run: |
        git config --global user.email sepamm1234@gmail.com
        git config --global user.name kidzz26
        git config --global credential.helper store
        echo "https://github.com/kidzz26:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa    
    - name: Setup tmate session
      timeout-minutes: 340
      continue-on-error: true
      uses: mxschmitt/action-tmate@master
    - name: Loop Workflow
      continue-on-error: true
      run: |
        # ${GITHUB_REPOSITORY} is the repo slug which runs this script
        git clone https://kidzz26${{ secrets.GH_TOKEN }}@github.com/ssh loop
        cd loop || exit 1
        echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
        git add looper.txt
        git commit -m "Workflow : Loop"
        git push -q https://kidzz26${{ secrets.GH_TOKEN }}@github.com/ssh HEAD:main  
